import React from 'react';
import { ExampleSlider } from './exampleSlider';
import { Ana1 } from './ana1';
import { Ana2 } from './ana2';
import { Ana3 } from './ana3';
import { Ana4 } from './ana4';
import { Ana5 } from './ana5';
import { Ana6 } from './ana6';
import { Ana7 } from './ana7';
import { Ana8 } from './ana8';
import { Ana9 } from './ana9';
import { Chartkit } from './chartkit';
import { HeroNew } from './hero-new';
import { HeroOld } from './hero-old';
import { M11 } from './m11';
import { M12 } from './m12';
import { M21 } from './m21';
import { M31 } from './m31';
import { M41 } from './m41';
import { M42 } from './m42';
import { M51 } from './m51';
import { M61 } from './m61';
import { M62 } from './m62';
import { M71 } from './m71';
import { M72 } from './m72';
import { M81 } from './m81';
import { M91 } from './m91';
import { M92 } from './m92';

export interface WidgetProps {
  chapterId: string;
  moduleId: string;
}

export const widgetRegistry: Record<string, React.FC<WidgetProps>> = {};
widgetRegistry['example-slider'] = ExampleSlider;
widgetRegistry['ana1'] = Ana1;
widgetRegistry['ana2'] = Ana2;
widgetRegistry['ana3'] = Ana3;
widgetRegistry['ana4'] = Ana4;
widgetRegistry['ana5'] = Ana5;
widgetRegistry['ana6'] = Ana6;
widgetRegistry['ana7'] = Ana7;
widgetRegistry['ana8'] = Ana8;
widgetRegistry['ana9'] = Ana9;
widgetRegistry['chartkit'] = Chartkit;
widgetRegistry['hero-new'] = HeroNew;
widgetRegistry['hero-old'] = HeroOld;
widgetRegistry['m11'] = M11;
widgetRegistry['m12'] = M12;
widgetRegistry['m21'] = M21;
widgetRegistry['m31'] = M31;
widgetRegistry['m41'] = M41;
widgetRegistry['m42'] = M42;
widgetRegistry['m51'] = M51;
widgetRegistry['m61'] = M61;
widgetRegistry['m62'] = M62;
widgetRegistry['m71'] = M71;
widgetRegistry['m72'] = M72;
widgetRegistry['m81'] = M81;
widgetRegistry['m91'] = M91;
widgetRegistry['m92'] = M92;
